############### Tasks  ################
GET http://localhost:3000/api/tasks

###
GET http://localhost:3000/api/tasks?page=0&size=3&title=dato

###
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title": "el titulo",
    "description": "tarea con titulo",
    "done": true
}

###
GET http://localhost:3000/api/tasks/60547e2f32a08b230cc0ce7c

###
DELETE http://localhost:3000/api/tasks/60547e2f32a08b230cc0ce7c

###
GET http://localhost:3000/api/tasks/done

###
PUT http://localhost:3000/api/tasks/60547537a257792cd0086ea4
Content-Type: application/json

{
    "title": "Actualizar un dato"
}



############### Users  ################

GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users?matricula=16020419

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "fullName": "Jesus Aguilera Magaña",
    "email": "al15020357@itsa.edu.mx",
    "tokenN": "pushToken[emuladoooo]"
}

###
GET http://localhost:3000/api/users/6054f1fb9f7b261784400b51

###
DELETE http://localhost:3000/api/users/6054f1fb9f7b261784400b51

###
# GET http://localhost:3000/api/users/done

###
PUT http://localhost:3000/api/users/6054f65637592d36c0375cb4
Content-Type: application/json

{
    "fullName": "Jesus Alejandro",
    "email": "al15020357@itsa.edu.mx",
    "tokenN": "pushToken[otrooo]"
}
