############### Tasks  ################
GET http://localhost:3000/api/tasks

###
GET http://localhost:3000/api/tasks?page=0&size=3&title=dato

###
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title": "el titulo",
    "description": "tarea con titulo",
    "done": true
}

###
GET http://localhost:3000/api/tasks/60547e2f32a08b230cc0ce7c

###
DELETE http://localhost:3000/api/tasks/60547e2f32a08b230cc0ce7c

###
GET http://localhost:3000/api/tasks/done

###
PUT http://localhost:3000/api/tasks/60547537a257792cd0086ea4
Content-Type: application/json

{
    "title": "Actualizar un dato"
}

############### TemporaryUsers localhost  ################
###  No olvides que para configurar las rutas de las peticiones debes revisar el puerto
###  Uso indiscriminadamente el 3000 y 3001 así que cuidado
###  También la ip que utilizo es localhost o proagrimex.com, ojo ajustalos de acuerdo al contexto
GET http://localhost:3001/api/v1/temporaryusers

###  get for id
GET http://localhost:3001/api/v1/temporaryusers/605adc6cbfb8af34609f348a

###  post full data
POST http://localhost:3001/api/v1/temporaryusers
Content-Type: application/json

{
    "usuario": "Manuel Aguilera Magaña", 
    "nombre": "Manuel",
    "apellidoPaterno": "Aguilera",
    "apellidoMaterno": "Magaña",
    "carrera": "Ing. Sistemas Computacionales", 
    "fechaNacimiento": {new Date("1997", "10", "15")},
    "sexo": "Hombre",
    "curp": "AUMM971015HMNGGN06",
    "estado": "Michoacán", 
    "municipio": "Apatzingán",
    "poblacion": "Apatzingán",
    "colonia": "Chandio",
    "direccion": "José María Morelos", 
    "numero": 222,
    "cp": 60710,
    "telefono1": 4531194027,
    "telefono2": 4531698688,
    "emailPersonal": "manuel.aguilera.magania@gmail.com",
    "tokenN": "",
    "matricula": 16020419,
    "planEstudios": "189480PAN",
    "fichaAceptada": false,   
    "pagoInscripcion": false,
}

###  post 
POST http://localhost:3001/api/v1/temporaryusers
Content-Type: application/json

{
    "usuario": "Jesus Alejandro", 
    "emailPersonal": "manuel_aguilerita@hotmail.com",
    "tokenN": "expoPushToken[784h9g389ghn98]"
}

###  post user institucional
POST http://localhost:3001/api/v1/users/nuevo
Content-Type: application/json

{
    "usuario": "Jesus Alejandro Aguilera Magaña",
    "email": "panchodelta1000@gmail.com",
    "emailPersonal": "al15020357@itsa.edu.mx",
    "tokenN": "ExponentPushToken[W13468LyTH5oRczdrMwAKg]"
}

###  delete temporaryuser
DELETE http://localhost:3001/api/v1/temporaryusers/605b26fbd391f41326b3065a

###  update temporaryuser
PUT http://localhost:3001/api/v1/temporaryusers/605adc6cbfb8af34609f348a
Content-Type: application/json

{
    "nombre": "funcinoa",
    "apellidoPaterno": "funcinoa",
    "apellidoMaterno": "funcinoa",
    "curp": "funcinoa",
    "telefono1": "funcinoa",
    "telefono2": "funcinoa",
    "sexo": "funcinoa",
    "fechaNacimiento": "2021-03-24T06:30:04.742Z"
}

############### TemporaryUsers  proagrimex.com ################

GET https://proagrimex.com/api/v1/temporaryusers

###
GET https://proagrimex.com/api/v1/temporaryusers/6054f1fb9f7b261784400b51

###
POST https://proagrimex.com/api/v1/temporaryusers
Content-Type: application/json

{
    "usuario": "Manuel Aguilera Magaña", 
    "nombre": "Manuel",
    "apellidoPaterno": "Aguilera",
    "apellidoMaterno": "Magaña",
    "carrera": "Ing. Sistemas Computacionales", 
    "fechaNacimiento": {new Date("1997", "10", "15")},
    "sexo": "Hombre",
    "curp": "AUMM971015HMNGGN06",
    "estado": "Michoacán", 
    "municipio": "Apatzingán",
    "poblacion": "Apatzingán",
    "colonia": "Chandio",
    "direccion": "José María Morelos", 
    "numero": 222,
    "cp": 60710,
    "telefono1": 4531194027,
    "telefono2": 4531698688,
    "emailPersonal": "manuel.aguilera.magania@gmail.com",
    "tokenN": "",
    "matricula": 16020419,
    "planEstudios": "189480PAN",
    "fichaAceptada": false,   
    "pagoInscripcion": false,
}

###
POST https://proagrimex.com/api/v1/temporaryusers
Content-Type: application/json

{
    "usuario": "Jesus Alejandro", 
    "emailPersonal": "manuel_aguilerita@hotmail.com",
    "tokenN": "expoPushToken[784h9g389ghn98]"
}

###
POST https://proagrimex.com/api/v1/users/nuevo
Content-Type: application/json

{
    "usuario": "Jesus Alejandro Aguilera Magaña",
    "email": "panchodelta1000@gmail.com",
    "emailPersonal": "al15020357@itsa.edu.mx",
    "tokenN": "ExponentPushToken[W13468LyTH5oRczdrMwAKg]"
}

###
DELETE https://proagrimex.com/api/v1/temporaryusers/605bff43d391f41326b3065d

###
PUT https://proagrimex.com/api/v1/temporaryusers/605c0efbecb400280e10730e
Content-Type: application/json

{
    "nombre": "funcinoa",
    "apellidoPaterno": "funcinoa",
    "apellidoMaterno": "funcinoa",
    "curp": "funcinoa",
    "telefono1": "funcinoa",
    "telefono2": "funcinoa",
    "sexo": "funcinoa",
    "fechaNacimiento": "funcinoa"
}

############### Carreras localhost ################

GET https://proagrimex.com/api/v1/carreras

###
GET https://proagrimex.com/api/v1/carreras/605c09a0008d703330f2b608

###
POST https://proagrimex.com/api/v1/carreras
Content-Type: application/json

{
    "carrera": "Ingenieria Industrial", 
    "planEstudios": "IIND2010-227", 
    "codigoCarrera": "IIND"
}

###
DELETE https://proagrimex.com/api/v1/carreras/605c0c79ecb400280e10730a

###
PUT https://proagrimex.com/api/v1/carreras/605c09a0008d703330f2b608
Content-Type: application/json

{
    "carrera": "Contador público", 
    "planEstudios": "COPU2010-205", 
    "codigoCarrera": "COPU"
}

############### TipoPagos proagrimex ################

GET https://proagrimex.com/api/v1/tipopagos

###
DELETE https://proagrimex.com/api/v1/tipopagos/605c2ca8546eb82d9a7a8278

###
POST https://proagrimex.com/api/v1/tipopagos
Content-Type: application/json

{
    "fichas": [
            "CAMBIO DE FICHA",
            "FICHA DE ADMISIÓN CONTADOR PUBLICO",
            "FICHA DE ADMISIÓN INGENIERIA EN GESTION EMPRESARIAL",
            "FICHA DE ADMISIÓN INGENIERIA BIOQUIMICA",
            "FICHA DE ADMISIÓN INGENIERIA  CIVIL",
            "FICHA DE ADMISIÓN INGENIERIA  INFORMATICA",
            "FICHA DE ADMISIÓN INGENIERIA  INDUSTRIAL",
            "FICHA DE ADMISION ING. EN INNOVACION AGRICOLA SUSTENTABLE",
            "FICHA DE ADMISIÓN ING. EN SISTEMAS COMPUTACIONALES"
    ], 
    "inscripcion": [
            "APORTACIÓN PARA EL FORTALECIMIENTO INSTITUCIONAL NUEVO INGRESO",
            "EXCEPCIÓN DE INSCRIPCION POR GRATUIDAD"
    ],
    "reinscripcion": [
            "APORTACIÓN PARA EL FORTALECIMIENTO INSTITUCIONAL REINGRESO",
            "EXCEPCIÓN DE REINSCRIPCION POR GRATUIDAD"
    ],
    "constanciasKardex": [
            "CONSTANCIA PARA RESIDENCIAS PROFESIONALES",
            "CONSTANCIA DE ESTUDIOS CON CALIFICACIONES",
            "CONSTANCIA DE ESTUDIOS SIN CALIFICACIONES",
            "KARDEX"
    ], 
    "tramitesEgreso": [
            "TRAMITE DE EGRESOS"
    ],
    "titulacion": [
            "CARTA DE PASANTE PAPEL OFICIAL",
            "CERTIFICADO OFICIAL (TERMINACIÓN DE ESTUDIOS)",
            "CERTIFICADO PARCIAL",
            "CURSO DE TITULACIÓN",
            "DUPLICADO DE CERTIFICADO",
            "REPOSICION DE ACTA DE EXÁMEN PROFESIONAL",
            "TITULO PROFESIONAL",
            "REPOSICION DE ACTA DE EXÁMEN PROFESIONAL"
    ],
    "ingles": [
            "CURSO DE INGLES INTERNO 13VO NIVEL (90hrs)",
            "CURSO DE INGLES INTERNO 2 NIVELES (90hrs)",
            "CURSO DE INGLES INTERNO 3 NIVELES (135hrs)",
            "CURSO DE INGLES INTERNO 4 NIVELES (180hrs)",
            "CONSTANCIA DE ESTUDIOS POR NIVEL CON CALIFICACIONES (INGLES INTERNO)",
            "CONSTANCIA DE LIBERACIÓN CON VALOR CURRICULAR POR REGISTRO DE CLE (INTERNOS)",
            "CONSTANCIA DE ESTUDIOS POR NIVEL (INGLES INTERNO)",
            "CUOTA ADICIONAL PÉRDIDA DE MATERIAL BIBLIOGRÁFICO",
            "CURSO DE ACREDITACIÓN DE INGLES",
            "CURSO DE INGLES INTERNO 1 NIVEL (45hrs)",
            "EXAMEN DE ACREDITACIÓN DE INGLES",
            "EXAMEN DE UBICACIÓN DE INGLES"
    ]
}


############### Periodos proagrimex ################

GET https://proagrimex.com/api/v1/periodos

###
GET https://proagrimex.com/api/v1/periodos/ultimo

###
POST https://proagrimex.com/api/v1/periodos
Content-Type: application/json

{
    "periodo": "20211-ENEJUL"
}

###
POST https://proagrimex.com/api/v1/periodos
Content-Type: application/json

{
    "periodo": "20203-JULDIC"
}

###
DELETE http://localhost:3001/api/v1/periodos/605c0c79ecb400280e10730a

###
PUT http://localhost:3001/api/v1/periodos/605c09a0008d703330f2b608
Content-Type: application/json

{
    "periodo": "20203-JULDIC"
}

############### Documentos proagrimex ################
POST https://proagrimex.com/api/v1/documentos
Content-Type: application/json

{
    "id_user": "605aeb952396130c36fbc43c"
}

###
DELETE https://proagrimex.com/api/v1/documentos/60653eb48e425509bd62fba2

############### Depositos bancarios proagrimex ################
POST https://proagrimex.com/api/v1/depositosbancarios
Content-Type: application/json

{
    "id": "605aeb952396130c36fbc43c",
    "tipoPago": "inscripcion",
    "concepto": "APORTACIÓN PARA EL FORTALECIMIENTO INSTITUCIONAL NUEVO INGRESO",
    "cantidad": "1",
    "costo": "800.00",
    "importe": "800.00",
    "convenioCIE": "001770500", 
    "observaciones": "No aplica" 
}

###
DELETE https://proagrimex.com/api/v1/depositosbancarios/6066dab91a0a391105f7c6fe

###
PUT https://proagrimex.com/api/v1/depositosbancarios/6066dc0030f91111be34b57c
Content-Type: application/json

{
    "procesado": false 
}

###
PUT https://proagrimex.com/api/v1/depositosbancarios/6066dc0030f91111be34b57c
Content-Type: application/json

{
    "id_user": "605aeb952396130c36fbc43c" 
}

###
PUT https://proagrimex.com/api/v1/depositosbancarios/6066e9bf30f91111be34b57d
Content-Type: application/json

{
    "id_user": "605aeb952396130c36fbc43c"
}

############### Users proagrimex ################

###
GET https://proagrimex.com/api/v1/users

###
POST https://proagrimex.com/api/v1/users
Content-Type: application/json

{
    "datosAlumno": {
        "nombre": "Manuel",
        "apellidoPaterno": "Aguilera",
        "apellidoMaterno": "Magaña",
        "tipoAlta": "inscripción",
        "estadoAlumno": "vigente",
        "carrera": "Ingenieria en Sistemas Computacionales",
        "fechaNacimiento": "15 octubre 1997",
        "curp": "AUMM971015HMNGGN06",
        "sexo": "HOMBRE",
        "tipoAlumno": "regular",
        "planEstudios": "ISIC2010-224",
        "tokenN": "ExponentPushToken[W13468LyTH5oRczdrMwAKg]",
        "fichaAceptada": "true",
        "pagoInscripcion": "true",
        "matricula": "16020419"
    },
    "datosGenerales": {
        "estado": "Michoacán",
        "municipio": "Apatzingán",
        "poblacion": "Chandio",
        "colonia": "Chandio",
        "direccion": "José María Morelos",
        "numero": "222",
        "cp": "60710",
        "telefono1": "4531194027",
        "telefono2": "4535389318",
        "emailPersonal": "manueleitor.information@gmail.com"
    },
    "procedencia": {
        "bachillerato": "COBAEM PLANTEL AGUILILLA",
        "especialidad": "Fisico-Matemático",
        "anioEgreso": "2016",
        "promedio": "100"
    },
    "datosFamiliares": {
        "padres": {
            "padre": {
                "nombre": "Jesús Aguilera García",
                "vive": true,
                "celular": "4531428237"
            },
            "madre": {
                "nombre": "Gloria Magaña Rodríguez",
                "vive": true,
                "celular": "4535389318"
            }
        }
    },
    "situacionActual": {
        "semestre": "1",
        "grupo": "A",
        "cargaMaxima": "32",
        "cargaMinima": "24",
        "creditosAprobados": "250",
        "promedioConReprobadas": "0.0",
        "promedioSinReprobadas": "0.0",
        "motivoBaja": "",
        "periodosMaximos": "12",
        "inscrito": "true",
        "fechaBajaDefinitiva": "",   
        "turno": "Matutino"   
    },
    "expedientes": {
        "residencias": {  
            "expediente": "RESIDENCIA LIBERADA",
            "liberado": false
        },        
        "acta": {  
            "expediente": "ACTA DE NACIMIENTO ORIGINAL",
            "liberado": false
        },        
        "certificado": {  
            "expediente": "CERTIFICADO DE BACHILLERATO LEGALIZADO",
            "liberado": false
        },        
        "curp": {  
            "expediente": "COPIA DE LA CURP",
            "liberado": false
        },        
        "ingles": {  
            "expediente": "ACREDITACIÓN DE INGLES",
            "liberado": false
        },        
        "constanciaNoAdeudo": {  
            "expediente": "CONSTANCIA DE NO ADEUDO",
            "liberado": false
        },        
        "fotografias": {  
            "expediente": "FOTOGRAFIAS (2 T/DIPLOMA Y 8 T/CREDENCIAL OVALADA)",
            "liberado": false
        },        
        "servicioSocial": {  
            "expediente": "SERVICIO SOCIAL",
            "liberado": false
        },        
        "pagoTitulacion": {  
            "expediente": "RECIBO DE PAGO DE TITULACIÓN",
            "liberado": false
        },        
        "ine": {  
            "expediente": "COPIA DEL INE",
            "liberado": false
        },        
        "vigenciaDerecho": {  
            "expediente": "VIGENCIA DE DERECHO",
            "liberado": false
        }        
    }
}

###
DELETE https://proagrimex.com/api/v1/users/606fb71107305e07352bca3d

###
DELETE http://localhost:3001/api/v1/users/605b2513018af4305cde48d6

###
PUT https://proagrimex.com/api/v1/users?id=606fb69207305e07352bca3a
Content-Type: application/json

{
    "id_temporaryUser": "605aeb952396130c36fbc43c"
}

###
PUT https://proagrimex.com/api/v1/users?id=606fb69207305e07352bca3a
Content-Type: application/json

{
    "id_temporaryUser": "605aeb952396130c36fbc43c"
}

###
PUT http://localhost:3001/api/v1/users?id=606fc066b31b0539ac030ff3
Content-Type: application/json

{
    "id_temporaryUser": "605aeb952396130c36fbc43c"
}

###
POST http://localhost:3001/api/v1/temporaryusers
Content-Type: application/json

{
    "emailPersonal": "al16020419@itsa.edu.mx"
}

############### Calificaciones localhost ################

###
GET http://localhost:3001/api/v1/calificaciones

###
POST http://localhost:3001/api/v1/calificaciones
Content-Type: application/json

{
    "id_user": "6070c561f6f07a02d02cd23f",
    "periodo": "20163-JULDIC",
    "claveMateria": "ACF0901",
    "materia": "CÁLCULO DIFERENCIAL",
    "unidades": "5",
    "estado": "Califs. parciales",
    "unidad1": "90",
    "unidad2": "90",
    "unidad3": "90",
    "unidad4": "90",
    "unidad5": "90",
    "unidad6": "0",
    "unidad7": "0",
    "unidad8": "0",
    "unidad9": "0",
    "unidad10": "0",
    "promedio": "90",
    "opc": "1a",
    "aprobadas": "AC",
    "tipoCurso": "NE"
}

###
POST http://localhost:3001/api/v1/calificaciones
Content-Type: application/json

{
    "id_user": "606fb69207305e07352bca3a",
    "periodo": "20163-JULDIC",
    "claveMateria": "ACC0906",
    "materia": "FUNDAMENTOS DE INVESTIGACIÓN",
    "unidades": "4",
    "estado": "Califs. parciales",
    "unidad1": "100",
    "unidad2": "100",
    "unidad3": "100",
    "unidad4": "100",
    "unidad5": "0",
    "unidad6": "0",
    "unidad7": "0",
    "unidad8": "0",
    "unidad9": "0",
    "unidad10": "0",
    "promedio": "100",
    "opc": "1a",
    "aprobadas": "AC",
    "tipoCurso": "NE"
}

###
POST http://localhost:3001/api/v1/calificaciones
Content-Type: application/json

{
    "id_user": "606fb69207305e07352bca3a",
    "periodo": "20163-JULDIC",
    "claveMateria": "AED128",
    "materia": "PROGRAMACIÓN ORIENTADA A OBJETOS",
    "unidades": "6",
    "estado": "Califs. parciales",
    "unidad1": "100",
    "unidad2": "100",
    "unidad3": "100",
    "unidad4": "100",
    "unidad5": "100",
    "unidad6": "94",
    "unidad7": "0",
    "unidad8": "0",
    "unidad9": "0",
    "unidad10": "0",
    "promedio": "99",
    "opc": "1a",
    "aprobadas": "AC",
    "tipoCurso": "NE"
}

###
PUT http://localhost:3001/api/v1/calificaciones/6070c2aae221ca272c0474ba
Content-Type: application/json

{
    "id_user": "6070bf64779e7d3c48b09299"
}

###
DELETE http://localhost:3001/api/v1/calificaciones/6070bf64779e7d3c48b09299
